// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhephgetoquqyffcbxgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoZXBoZ2V0b3F1cXlmZmNieGd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NDYwNjEsImV4cCI6MjA3MjEyMjA2MX0.ZlGlG8Z2myXyztQiGa9hiRr46h5sQlaC7GF3Aw4U_qE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});